[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
  python_version = "2.7"
  environment = { PATH = "/usr/bin/python2:$PATH" }
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
