backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

# when using the default proxy server port
local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "project"
    label: "Project Page"
    create: true #user can create new pages of this type
    folder: "src/pages/project"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "project-page",
        }
      - { label: Title, name: title, widget: string }
      - { label: MainImage, name: mainImage, widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Video Url",
          name: "videoUrl",
          widget: "string",
          required: false,
        }
      - {
          label: Gallery,
          name: gallery,
          widget: list,
          fields:
            [
              { label: Image, name: image, widget: image },
              { label: Alt, name: alt, widget: string },
            ],
        }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Image, name: image, widget: image }
          - {
              label: Bios,
              name: bios,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Name, name: name, widget: string },
                  { label: Blurb, name: blurb, widget: string },
                ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/projects/index.md"
        label: "Projects Page"
        name: "projects"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "projects-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
